@url = https://localhost:7001
@accessToken = 

###

GET {{url}}/api/cart HTTP/1.1
Authorization: Bearer {{accessToken}}

###

POST {{url}}/api/cart/finalize HTTP/1.1
Authorization: Bearer {{accessToken}}

###

POST {{url}}/api/cart/clear HTTP/1.1
Authorization: Bearer {{accessToken}}

###

POST {{url}}/api/cart/add HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "OfferId": "{{offerId}}",
    "Quantity": 5
}