@productsUrl = https://localhost:5001

###

GET {{productsUrl}}/api/products HTTP/1.1

### 
POST {{productsUrl}}/api/products HTTP/1.1
Content-Type:  application/json

{
    "Name": "Some product4",
    "Price": 10.00
}