@url = https://localhost:10000

###

POST {{url}}/offers-api/healthcheck HTTP/1.1

###

POST {{url}}/identity-api/healthcheck HTTP/1.1

###

POST {{url}}/carts-api/healthcheck HTTP/1.1

###

POST {{url}}/orders-api/healthcheck HTTP/1.1

###