@url = http://localhost:6000
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJUb2tlbklkIjoiZTIzMjc1M2YtMDkzNi00YmQwLWIyNjUtOTk2Njk3NmI0M2M5IiwiVXNlcklkIjoiOTUzZTkyMmQtYjRiZC00ZTA5LTllNjctNDNiZWViZDU5ZjM2IiwiRW1haWwiOiJhZG1pbkBtYWlsLmNvbSIsIlJvbGUiOiJhZG1pbiIsImV4cCI6MTYxMDY0NzI1MCwiaXNzIjoiSWRlbnRpdHkuQVBJIiwiYXVkIjoiSWRlbnRpdHkuQVBJLkF1ZGllbmNlIn0.WnhvJt9DbbLDKft_aeuYSWD2WXn3A7xWLFBBfrNXQ18
@userIdToBlock = F48D2D7B-D3C1-4FB7-7DA6-08D8B32F146C

### Lock

POST {{url}}/api/admin/lock HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "UserId": "{{userIdToBlock}}",
    "LockUntil": "2030-12-31T23:59"
}

### Unlock

POST {{url}}/api/admin/unlock HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "UserId": "{{userIdToBlock}}"
}