@url = https://localhost:6001

### Sign up

POST {{url}}/api/auth/sign-up HTTP/1.1
Content-Type: application/json

{
    "email": "user@mail.com",
    "password": "Test123",
    "firstName": "SomeFirstName",
    "lastName": "SomeLastName"
}

### Sign in

POST {{url}}/api/auth/sign-in HTTP/1.1
Content-Type: application/json

{
    "email": "user@mail.com",
    "password": "Test123"
}

### Admin sign-in

POST {{url}}/api/auth/sign-in HTTP/1.1
Content-Type: application/json

{
    "email": "admin@mail.com",
    "password": "Test1234"
}