@url = http://localhost:6000

### Sign up

POST {{url}}/api/auth/sign-up HTTP/1.1
Content-Type: application/json

{
    "email": "user@mail.com",
    "password": "Test1234"
}

### Sign in

POST {{url}}/api/auth/sign-in HTTP/1.1
Content-Type: application/json

{
    "email": "user@mail.com",
    "password": "Test1234"
}

### Admin sign-in

POST {{url}}/api/auth/sign-in HTTP/1.1
Content-Type: application/json

{
    "email": "admin@mail.com",
    "password": "Test1234"
}