@url = http://localhost:6000
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJUb2tlbklkIjoiZTVmNDkxMWQtNTIxYy00MDgzLWE2N2ItZGU1ZDIyYjk0OGEwIiwiVXNlcklkIjoiZGUzNmY0ZDItNDRkNi00ZDhhLTJlMTAtMDhkOGQ3NTk4ODQzIiwiRW1haWwiOiJ1c2VyM0BtYWlsLmNvbSIsIlJvbGUiOiJ1c2VyIiwiZXhwIjoxNjE1MjI0NjEzLCJpc3MiOiJJZGVudGl0eS5BUEkiLCJhdWQiOiJJZGVudGl0eS5BUEkuQXVkaWVuY2UifQ.a2h7uuUUqEw50qUJjRNQfFKXF_BZtBuD59n6bCUNaxY
@deliveryAddressId = a322294a-53b8-47d1-ab5c-9c9f06ae11d2

###

GET {{url}}/api/delivery-addresses HTTP/1.1
Authorization: Bearer {{accessToken}}

### Create 1

POST {{url}}/api/delivery-addresses HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "FirstName": "Jan",
    "LastName": "Ryba-Okoń",
    "PhoneNumber": "+48 123 456 789",
    "Country": "Poland",
    "City": "Poznań",
    "ZipCode": "21-370",
    "Street": "Jana Pawła II 37a/21",
    "IsPrimary": true
}

### Create 2

POST {{url}}/api/delivery-addresses HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "FirstName": "Jan",
    "LastName": "Ryba-Okoń",
    "PhoneNumber": "+48 987 654 321",
    "Country": "Poland",
    "City": "Krakow",
    "ZipCode": "21-370",
    "Street": "Jana Pawła II 37a/21",
    "IsPrimary": true
}


### Update 1

PUT {{url}}/api/delivery-addresses HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "DeliveryAddressId": "{{deliveryAddressId}}",
    "Street": "Jana Pawła II 37a/22",
    "IsPrimary": true
}

### Update 2

PUT {{url}}/api/delivery-addresses HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "DeliveryAddressId": "{{deliveryAddressId}}",
    "LastName": "Ryba-Okońń",
    "PhoneNumber": "+48 123456789",
    "Street": "Jana Pawła II 37a/22"
}

### Remove

DELETE {{url}}/api/delivery-addresses HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "DeliveryAddressId": "{{deliveryAddressId}}"
}
