@url = https://localhost:6001

### Invalid email

POST {{url}}/api/password/generate/reset-token HTTP/1.1
Content-Type: application/json

"not-existing-user@mail.com"

###

POST {{url}}/api/password/generate/reset-token HTTP/1.1
Content-Type: application/json

"user@mail.com"

### Invalid request

POST {{url}}/api/password/reset HTTP/1.1
Content-Type: application/json

{
    "NewPassword": "invalid"
}

###

@resetToken = 

POST {{url}}/api/password/reset HTTP/1.1
Content-Type: application/json

{
    "ResetToken": "{{resetToken}}",
    "NewPassword": "Test123"
}