@url = http://localhost:6000
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJUb2tlbklkIjoiMmZjMTczZjMtYmUzZS00ZGJiLWI2N2ItMWU1MzNiYjY2YTFmIiwiVXNlcklkIjoiODBlN2YxZDYtYjU1NC00ODA0LTdhMmUtMDhkOGQwNGVhNWMzIiwiRW1haWwiOiJ1c2VyQG1haWwuY29tIiwiUm9sZSI6InVzZXIiLCJleHAiOjE2NzMyNDE1NDgsImlzcyI6IklkZW50aXR5LkFQSSIsImF1ZCI6IklkZW50aXR5LkFQSS5BdWRpZW5jZSJ9.4Mr-EMB1Bw-feYnFJMlUyQ7LamDC2hyCQ3Fxp72SQC

###

GET {{url}}/api/profile-info HTTP/1.1
Authorization: Bearer {{accessToken}}

### Invalid data #1

PUT {{url}}/api/profile-info HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "DateOfBirth": "20.01.2020"
}

### Invalid data #2

PUT {{url}}/api/profile-info HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "DateOfBirth": "1929-01-01"
}

### Invalid data #3

PUT {{url}}/api/profile-info HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "FirstName": "1s",
    "LastName": "sA",
    "PhoneNumber": "1"
}

### Valid data #1

PUT {{url}}/api/profile-info HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "FirstName": "Joe",
    "LastName": "Doe",
    "PhoneNumber": "123 456 789",
    "DateOfBirth": "1990-10-12"
}