@url = http://localhost:6000
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJUb2tlbklkIjoiZmM0MzhiOTEtYjI2YS00MGRhLWI1YWEtNzgzMGE2MzFhZDg0IiwiVXNlcklkIjoiYmEwOWNlNjctYjI4MC00NTliLTlhNDgtMDhkOGFlNWI5MDA3IiwiRW1haWwiOiJ1c2VyQG1haWwuY29tIiwiUm9sZSI6InVzZXIiLCJleHAiOjE2MTAxNDExNzYsImlzcyI6IklkZW50aXR5LkFQSSIsImF1ZCI6IklkZW50aXR5LkFQSS5BdWRpZW5jZSJ9.XKQC_1Hgxy0G7Qb1VUueiGB_8JoiCVsIHkGm-OlPuKw

### Invalid data #1

PUT {{url}}/api/ProfileInfo HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "DateOfBirth": "20.01.2020"
}

### Invalid data #2

PUT {{url}}/api/ProfileInfo HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "DateOfBirth": "1929-01-01"
}

### Invalid data #3

PUT {{url}}/api/ProfileInfo HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "FirstName": "1s",
    "LastName": "sA",
    "PhoneNumber": "1"
}

### Valid data #1

PUT {{url}}/api/ProfileInfo HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "FirstName": "Joe",
    "LastName": "Doe",
    "PhoneNumber": "123 456 789",
    "DateOfBirth": "1990-10-12"
}