@url = http://localhost:6000
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJUb2tlbklkIjoiOGYxZGIxNjYtZjE4Yy00NWYyLTgzNTktZDIyMmQzYjliMmRhIiwiVXNlcklkIjoiYmEwOWNlNjctYjI4MC00NTliLTlhNDgtMDhkOGFlNWI5MDA3IiwiRW1haWwiOiJ1c2VyQG1haWwuY29tIiwiUm9sZSI6InVzZXIiLCJleHAiOjE2NzE0MDkyNTQsImlzcyI6IklkZW50aXR5LkFQSSIsImF1ZCI6IklkZW50aXR5LkFQSS5BdWRpZW5jZSJ9.heCDM4ATRWPJ2mDxRi3qh4fvbMeegBhwURYOZGvDLGA
@sellerId = BA09CE67-B280-459B-9A48-08D8AE5B9007

###

GET {{url}}/api/seller/{{sellerId}} HTTP/1.1

###

GET {{url}}/api/seller/bank-account/my HTTP/1.1
Authorization: Bearer {{accessToken}}

###

PUT {{url}}/api/seller HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "ContactEmail": "contact@mail.com",
    "BankAccountNumber": "82 1020 5226 0000 6102 0417 7895",
    "AdditionalInfo": "Nothing more here"
}