@url = https://localhost:6001
@accessToken = 
@refreshToken = 

###

POST {{url}}/api/token/decode/access-token HTTP/1.1
Content-Type: application/json

"{{accessToken}}"

###

POST {{url}}/api/token/decode/refresh-token HTTP/1.1
Content-Type: application/json

"{{refreshToken}}"

###

POST {{url}}/api/token/verify/refresh-token HTTP/1.1
Content-Type: application/json

"{{refreshToken}}"

###

POST {{url}}/api/token/refresh/access-token HTTP/1.1
Content-Type: application/json

"{{refreshToken}}"

###

POST {{url}}/api/token/revoke/refresh-token HTTP/1.1
Content-Type: application/json

"{{refreshToken}}"