@url = http://localhost:6000
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJUb2tlbklkIjoiODQ5NWVmYTEtMzMyNC00OWEwLWE5NzgtYWY4NWQ0NTk4ODkyIiwiVXNlcklkIjoiYmEwOWNlNjctYjI4MC00NTliLTlhNDgtMDhkOGFlNWI5MDA3IiwiRW1haWwiOiJ1c2VyQG1haWwuY29tIiwiUm9sZSI6InVzZXIiLCJleHAiOjE2MTA5OTQyMDgsImlzcyI6IklkZW50aXR5LkFQSSIsImF1ZCI6IklkZW50aXR5LkFQSS5BdWRpZW5jZSJ9.FU2pjd-Q8SgOZigbnejnA-5l_SoAF1G55UZbZHopeiM

###

GET {{url}}/api/user/me HTTP/1.1
Authorization: Bearer {{accessToken}}