@url = http://localhost:8000
###

POST {{url}}/api/order/cancel HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "OrderId": "{{orderId}}"
}

###

GET {{url}}/api/order/{{orderId}}/transfer/details HTTP/1.1
Authorization: Bearer {{accessToken}}
