@url = http://localhost:8000
@accessToken = 
@orderId = 

###

POST {{url}}/api/orders/cancel HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "OrderId": "{{orderId}}"
}

###

GET {{url}}/api/orders/{{orderId}}/transfer/details HTTP/1.1
Authorization: Bearer {{accessToken}}
