@url = http://localhost:8000
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJUb2tlbklkIjoiNWU0ZGFhMWEtZDliNC00YmFmLWI3ODMtMjdiOWI5NmNkODUwIiwiVXNlcklkIjoiODBlN2YxZDYtYjU1NC00ODA0LTdhMmUtMDhkOGQwNGVhNWMzIiwiRW1haWwiOiJ1c2VyQG1haWwuY29tIiwiUm9sZSI6InVzZXIiLCJleHAiOjE2MTQ4NzU4ODUsImlzcyI6IklkZW50aXR5LkFQSSIsImF1ZCI6IklkZW50aXR5LkFQSS5BdWRpZW5jZSJ9.78gj8fIW0uNLR7lLw-pxXtholJqU2GznG9GSnc8LPGk
@orderId = ebff8a49-14a1-4d61-4929-08d8d5928ce9

###

GET {{url}}/api/orders HTTP/1.1
Authorization: Bearer {{accessToken}}

###

GET {{url}}/api/orders/{{orderId}}/transfer/details HTTP/1.1
Authorization: Bearer {{accessToken}}

###

POST {{url}}/api/orders/cancel HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "OrderId": "{{orderId}}"
}

###

PUT {{url}}/api/orders/delivery HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "OrderId": "{{orderId}}",
    "FirstName": "FirstName",
    "LastName": "LastName",
    "PhoneNumber": "123 456 789",
    "Country": "Poland",
    "City": "Krakow",
    "ZipCode": "07-410",
    "Street": "Jana Pawla 21/37"
}
