@url = http://localhost:8000
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJUb2tlbklkIjoiMTJmY2JhMjctYjA3Ni00YzY1LWI3YzktYzRmNzcyYmMyM2MwIiwiVXNlcklkIjoiYmEwOWNlNjctYjI4MC00NTliLTlhNDgtMDhkOGFlNWI5MDA3IiwiRW1haWwiOiJ1c2VyQG1haWwuY29tIiwiUm9sZSI6InVzZXIiLCJleHAiOjE2MTAzODQ5NjcsImlzcyI6IklkZW50aXR5LkFQSSIsImF1ZCI6IklkZW50aXR5LkFQSS5BdWRpZW5jZSJ9.MvXMV4YDO7aLM9liEb8wCxGFShjba-v4fJkK4myKCrI
@orderId = 4FD7C54F-FBB8-4CB9-EC82-08D8B4C1116E

###

POST {{url}}/api/order/cancel HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "OrderId": "{{orderId}}"
}

###

GET {{url}}/api/order/{{orderId}}/transfer/details HTTP/1.1
Authorization: Bearer {{accessToken}}
