@url = http://localhost:5000
### Immortal access token
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJUb2tlbklkIjoiOGYxZGIxNjYtZjE4Yy00NWYyLTgzNTktZDIyMmQzYjliMmRhIiwiVXNlcklkIjoiYmEwOWNlNjctYjI4MC00NTliLTlhNDgtMDhkOGFlNWI5MDA3IiwiRW1haWwiOiJ1c2VyQG1haWwuY29tIiwiUm9sZSI6InVzZXIiLCJleHAiOjE2NzE0MDkyNTQsImlzcyI6IklkZW50aXR5LkFQSSIsImF1ZCI6IklkZW50aXR5LkFQSS5BdWRpZW5jZSJ9.heCDM4ATRWPJ2mDxRi3qh4fvbMeegBhwURYOZGvDLGA
@offerId = daa0fd21-3000-48c7-afa5-08d8ae5ca027
@categoryId = ccf260b6-b73a-4294-d6ab-08d8af4dc126

###

GET {{url}}/api/offers?fromPrice=48&toPrice=54&pageSize=20&pageIndex=1 HTTP/1.1

### 

GET {{url}}/api/offers/my?pageSize=20&pageIndex=1 HTTP/1.1
Authorization: Bearer {{accessToken}}

###

GET {{url}}/api/offers/{{offerId}} HTTP/1.1

### 

POST {{url}}/api/offers HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type:  application/json

{
    "Name": "Offer {{$datetime iso8601}}",
    "Description": "Some offer {{$datetime iso8601}}",
    "Price": {{$randomInt 1 100}},
    "TotalStock": {{$randomInt 5 20}},
    "CategoryId": "{{categoryId}}"
}

###

PUT  {{url}}/api/offers HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type:  application/json

{
    "OfferId": "{{offerId}}",
    "Name": "Some name {{$datetime iso8601}}",
    "Description": "Some offer {{$datetime iso8601}}",
    "Price": 52
}

###

POST {{url}}/api/offers/end HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "OfferId": "{{offerId}}"
}

###

DELETE  {{url}}/api/offers HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type:  application/json

{
    "OfferId": "{{offerId}}"
}