@url = http://localhost:5000
@adminAccessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJUb2tlbklkIjoiNjJiMWZjMGYtMGVhMy00NWYwLTk5ZDgtODZlNDhhNDlmNWZiIiwiVXNlcklkIjoiOTUzZTkyMmQtYjRiZC00ZTA5LTllNjctNDNiZWViZDU5ZjM2IiwiRW1haWwiOiJhZG1pbkBtYWlsLmNvbSIsIlJvbGUiOiJhZG1pbiIsImV4cCI6MTYxMjQ1ODI0NiwiaXNzIjoiSWRlbnRpdHkuQVBJIiwiYXVkIjoiSWRlbnRpdHkuQVBJLkF1ZGllbmNlIn0.bDYntiEvhCbuQ3juJ3e-T-gSY_UgH0Fekns_bj5K5jg

###

GET {{url}}/api/delivery-methods/ HTTP/1.1

###

@deliveryMethodId = 714cdf36-059a-495f-b1f3-08d8b6635dad

GET {{url}}/api/delivery-methods/{{deliveryMethodId}} HTTP/1.1

###

POST {{url}}/api/delivery-methods HTTP/1.1
Authorization: Bearer {{adminAccessToken}}
Content-Type: application/json

{
    "Name": "Odbiór osobisty",
    "Price": 0
}

###

PUT {{url}}/api/delivery-methods HTTP/1.1
Authorization: Bearer {{adminAccessToken}}
Content-Type: application/json

{
    "DeliveryMethodId": "{{deliveryMethodId}}",
    "Name": "DHL",
    "Description": "Some desc {{$datetime iso8601}}",
    "Price": 12.00
}