@url = http://localhost:5000
@adminAccessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJUb2tlbklkIjoiM2ZlNTc5NzAtYzczYi00MTFkLWE5MWQtNjNhY2Q4ZDk1ZjM5IiwiVXNlcklkIjoiOTUzZTkyMmQtYjRiZC00ZTA5LTllNjctNDNiZWViZDU5ZjM2IiwiRW1haWwiOiJhZG1pbkBtYWlsLmNvbSIsIlJvbGUiOiJhZG1pbiIsImV4cCI6MTY3MzI0MTM4NiwiaXNzIjoiSWRlbnRpdHkuQVBJIiwiYXVkIjoiSWRlbnRpdHkuQVBJLkF1ZGllbmNlIn0.I1PcLFEcW_1bH6idHELq0prvsQ-20rG7r3k_sCrnY0M
@deliveryMethodId = 04fd8890-6f5a-4194-c31f-08d8d0526bab

###

GET {{url}}/api/delivery-methods/ HTTP/1.1

###

GET {{url}}/api/delivery-methods/{{deliveryMethodId}} HTTP/1.1

###

POST {{url}}/api/delivery-methods HTTP/1.1
Authorization: Bearer {{adminAccessToken}}
Content-Type: application/json

{
    "Name": "Pickup in person",
    "Price": 0
}

###

PUT {{url}}/api/delivery-methods HTTP/1.1
Authorization: Bearer {{adminAccessToken}}
Content-Type: application/json

{
    "DeliveryMethodId": "{{deliveryMethodId}}",
    "Name": "Poczta Polska",
    "Description": "Some desc {{$datetime iso8601}}",
    "Price": 10.00
}

###

DELETE {{url}}/api/delivery-methods HTTP/1.1
Authorization: Bearer {{adminAccessToken}}
Content-Type: application/json

{
    "DeliveryMethodId": "{{deliveryMethodId}}"
}